### ISSUE TITLE
Focus on text input keeps returning to first input when typing

### ISSUE THREAD

**Issue by Shrreya** [kirekire95/GraphQL-Server-MERNG-Client#2]
**Issue description:** On Register page, after typing into the username input, on typing into password focus goes back to username.

**Possible cause:** State changes are causing the component tree to re-render, this is probably due to how Reach Router handles function components. After each render, the `autofocus` property on the first input causes the focus to return there.

**Possible solution:** To maintain focus on the input currently being typed into, the `useRef` and `useEffect` hooks can be utilised, as in the sample code below:
```
const [currentInput, setCurrentInput] = useState("username")
const usernameRef = useRef()
const passwordRef = useRef()

useEffect(() => {
    switch(currentInput) {
      case "username": 
        usernameRef.current.focus()
        break
      case "password": 
        passwordRef.current.focus()
    }
  })
```

Add this line within the `handleChange` event handler function to keep record of the currently focussed input:
```
setCurrentInput(event.target.name)
```

Add the props `ref={usernameRef}` and `ref={passwordRef}` for the `username` and `password` inputs respectively.

Refer [this related issue](https://github.com/reach/router/issues/227) on the Reach Router repo.

**Comment by kirekire95** [comment]
Fixed!
